 spring.datasource.url=jdbc:postgresql://localhost:5432/study_planner
spring.datasource.username=postgres
spring.datasource.password=PRYM2026#1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true